- name: This playbook for Package Management
  hosts: 
    - linux

  pre_tasks:
    - debug: 
        msg: "Start Playbook"

  roles:
    - datadisk-n01619861
    - profile-n01619861
    - user-n01619861
    - webserver-n01619861

  post_tasks:
    - debug: 
        msg: "Playbook Completed Successfully"

