- name: Create user accounts
  hosts: linux
  become: yes
  vars:
    start_uid: 5001
  tasks:
    - name: Create users
      user:
        name: "user{{ item }}"
        uid: "{{ start_uid + (item | int) - 1 }}"
        state: present
      loop: "{{ range(101, 111) | list }}"
