- name: Install
  hosts: linux-host2
  become: true
  tasks:
    - name: Install Apache
      package:
        name: "{{ 'apache2' if ansible_distribution == 'Ubuntu' else 'httpd' }}"
        state: present
      notify:
        - restart apache
        - enable apache

    - name: Install MariaDB
      package:
        name: mariadb-server
        state: present
      notify:
        - restart mariadb
        - enable mariadb

  handlers:
    - name: restart apache
      service:
        name: "{{ 'apache2' if ansible_distribution == 'Ubuntu' else 'httpd' }}"
        state: restarted

    - name: enable apache
      service:
        name: "{{ 'apache2' if ansible_distribution == 'Ubuntu' else 'httpd' }}"
        enabled: yes

    - name: restart mariadb
      service:
        name: mariadb
        state: restarted

    - name: enable mariadb
      service:
        name: mariadb
        enabled: yes

