---
- name: timezone
  hosts: linux-host2
  tasks:
    - name: Set timezone
      timezone:
        name: America/Edmonton

    - name: Create devops group
      group:
        name: devops
        state: present

    - name: Create devops1 user
      user:
        name: devops1
        uid: 2500
        groups: devops
        state: present

