- name: Playbook
  hosts: linux-host1
  vars:
    grouplist1: group10
    grouplist2: group20
    userlist1: user10
    userlist2: user20
  tasks:
    - name: Create group10
      group:
        name: "{{ grouplist1 }}"
        state: present

    - name: Create group20
      group:
        name: "{{ grouplist2 }}"
        state: present

    - name: Create user10
      user:
        name: "{{ userlist1 }}"
        uid: 1800
        groups: "{{ grouplist1 }}"
        state: present

    - name: Create user20
      user:
        name: "{{ userlist2 }}"
        uid: 1900
        shell: /bin/bash
        home: "/home/{{ userlist2 }}"
        groups: "{{ grouplist2 }}"
        state: present

